steps:
  #Execute SonarCloud Scan
  - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=aceein-gcpdevsecops','-Dsonar.projectKey=aceein-gcpdevsecops','-Dsonar.token=${_SONAR_TOKEN}']
steps:   
  #Run Software Composition Analysis (SCA security scan) using Snyk
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: Snyk SCA
options:
  logging: CLOUD_LOGGING_ONLY
