steps:
  #Execute SonarCloud Scan
  - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=aceein-gcpdevsecops','-Dsonar.projectKey=aceein-gcpdevsecops','-Dsonar.token=${_SONAR_TOKEN}']
  - name: 'ubuntu'
    entrypoint: bash
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: Snyk SCA
    - name: 'ubuntu'
    entrypoint: bash
    args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.17.0/ZAP_2.17.0_Linux.tar.gz
        tar -xvf ZAP_2.17.0_Linux.tar.gz
        cd ZAP_2.17.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html 
    id: DAST Scan using OWASP ZAP
artifacts:
  objects:
    location: 'gs://aceein'
    paths:
      - zap_report.html
options:
  logging: CLOUD_LOGGING_ONLY
