steps:
  #Execute SonarCloud Scan
  - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=aceein-gcpdevsecops','-Dsonar.projectKey=aceein-gcpdevsecops','-Dsonar.token=${_SONAR_TOKEN}']
options:
  logging: CLOUD_LOGGING_ONLY
